conf/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("cooking.urls", namespace="cooking")),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cooking/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from rest_framework_simplejwt.views import (
    TokenObtainPairView, TokenRefreshView
)

from cooking import views

app_name = "cooking"

urlpatterns = [
    # path("", cache_page(60 * 3)(views.Index.as_view()), name="index"), # Хешування на базі index.html
    path("", views.Index.as_view(), name="index"),
    path(
        "category/<int:pk>/",
        views.ArticleByCategory.as_view(),
        name="category_list"
    ),
    path("post/<int:pk>", views.PostDetail.as_view(), name="post_detail"),
    path("add_arcticle/", views.AddPost.as_view(), name="add_post"),
    path("post/<int:pk>/update/", views.UpdatePost.as_view(), name="post_update"),
    path("post/<int:pk>/delete/", views.DeletePost.as_view(), name="post_delete"),
    path("search/", views.SearchResult.as_view(), name="search"),
    path(
        "password/",
        views.UserChangePassword.as_view(),
        name="change_password",
    ),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("register/", views.user_register, name="register"),
    path("add_comment/<int:post_id>/", views.add_comment, name="add_comment"),
    path("profile/<int:user_id>/", views.profile, name="profile"),

    # API
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("posts/api/", views.CookingAPI.as_view(), name="cooking_api"),
    path("posts/api/<int:pk>", views.CookingAPIDetail.as_view(), name="cooking_api_detail"),
    path("categories/api/", views.CategoryAPI.as_view(), name="category_api"),
    path("categories/api/<int:pk>", views.CategoryAPIDetail.as_view(), name="category_api_detail"),
]

cooking/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Category(models.Model):
    """Категорія новин"""

    title = models.CharField(max_length=255, verbose_name="Назва категорії")

    class Meta:
        db_table = "category"
        verbose_name = "Категорія"
        verbose_name_plural = "Категорії"

    def get_absolute_url(self):
        return reverse("cooking:category_list", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title


class Post(models.Model):
    """Для постів"""

    title = models.CharField(max_length=255, verbose_name="Назва")
    content = models.TextField(
        default="Скоро буде стаття...", verbose_name="Контент"
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата створення"
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата оновлення"
    )
    photo = models.ImageField(
        upload_to="photos/", blank=True, null=True, verbose_name="Зображення"
    )
    watched = models.IntegerField(
        default=0, verbose_name="Кількість переглядів"
    )
    is_published = models.BooleanField(
        default=True, verbose_name="Опубліковано?"
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name="Категорія",
    )
    author = models.ForeignKey(
        User,
        default=None,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name="Автор статті"
    )

    class Meta:
        db_table = "post"
        verbose_name = "Пост"
        verbose_name_plural = "Пости"

    def get_absolute_url(self):
        return reverse("cooking:post_detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    """Коментарі к статтям"""
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Стаття"
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="Користувач"
    )
    text = models.TextField(verbose_name="Коментар")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата створення")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата оновлення")

    class Meta:
        db_table = "Comment"
        verbose_name = "Коментар"
        verbose_name_plural = "Коментарі"
        ordering = ["-created_at"]

    def __str__(self):
        return self.text

cooking/forms.py
from django import forms
from .models import Post, Comment
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class PostAddForm(forms.ModelForm):
    """Форма для додавання статті від користувача"""

    class Meta:
        model = Post
        fields = ["title", "content", "photo", "category"]
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "content": forms.Textarea(attrs={"class": "form-control"}),
            "photo": forms.FileInput(attrs={"class": "form-control"}),
            "category": forms.Select(attrs={"class": "form-control"}),
        }


class LoginForm(AuthenticationForm):
    """Форма для аутентифікації користувача"""

    username = forms.CharField(
        label="Ім'я користувача",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    password = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
    )


class RegistrationForm(UserCreationForm):
    """Форма для реєстрації користувача"""

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    username = forms.CharField(
        max_length=150,
        label="Ім'я користувача",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Ім'я користувача"}
        ),
    )
    email = forms.CharField(
        max_length=150,
        label="Email",
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "Введіть ваш email"}
        ),
    )
    password1 = forms.CharField(
        max_length=150,
        label="Пароль",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Пароль"}
        ),
    )
    password2 = forms.CharField(
        max_length=150,
        label="Підтвердження пароля",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "Підтвердіть пароль",
            }
        ),
    )


class CommentForm(forms.ModelForm):
    """Форма для написання коментарів"""

    class Meta:
        model = Comment
        fields = ["text"]

        widgets = {
            "text": forms.Textarea(attrs={
                "class": "form-control", "placeholder": "Текст вашого коментаря"
            })}

cooking/views.py
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.db.models import F, Q
from django.contrib.auth import login, logout
from django.contrib import messages
from django.views import generic
from django.contrib.auth.views import PasswordChangeView
from rest_framework.generics import ListAPIView, RetrieveAPIView
from rest_framework.permissions import IsAuthenticated

from .forms import PostAddForm, LoginForm, RegistrationForm, CommentForm
from .models import Post, Category, Comment
from .serializers import PostSerializer, CategorySerializer

# def index(request: HttpRequest) -> HttpResponse:
#     """Для головної сторінки"""
#     posts = Post.objects.all()
#     categories = Category.objects.all()
#     context = {
#         "title": "Головна сторінка",
#         "posts": posts,
#         "categories": categories,
#     }
#     return render(request, "cooking/_index.html", context)


class Index(generic.ListView):
    """Для головної сторінки"""

    model = Post
    context_object_name = "posts"
    template_name = "cooking/_index.html"
    extra_context = {"title": "Головна сторінка"}


# def category_list(request: HttpRequest, pk: int) -> HttpResponse:
#     """Реакція на натискання кнопки категорії"""
#     posts = Post.objects.filter(category_id=pk)
#     categories = Category.objects.all()
#     context = {
#         "title": posts[0].category,
#         "posts": posts,
#         "categories": categories,
#     }
#     return render(request, "cooking/_index.html", context)


class ArticleByCategory(Index):
    """Реакція на натискання кнопки категорії"""

    def get_queryset(self):
        return Post.objects.filter(
            category_id=self.kwargs["pk"], is_published=True
        )

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()  # context = {}
        category = Category.objects.get(pk=self.kwargs["pk"])
        context["title"] = category.title
        return context


# def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
#     """Сторінка статті"""
#     article = Post.objects.get(pk=pk)
#     recommendation = Post.objects.exclude(pk=pk).order_by("-watched")[:5]
#     Post.objects.filter(pk=pk).update(watched=F("watched") + 1)
#     context = {
#         "title": article.title,
#         "post": article,
#         "recommend": recommendation,
#     }
#     return render(request, "cooking/_article_detail.html", context)


class PostDetail(generic.DetailView):
    """Сторінка статті"""

    model = Post
    template_name = "cooking/_article_detail.html"

    def get_queryset(self):
        post = Post.objects.filter(pk=self.kwargs["pk"])
        return post

    def get_context_data(self, **kwargs):
        context = super().get_context_data()  # context = {}
        Post.objects.filter(pk=self.kwargs["pk"]).update(
            watched=F("watched") + 1
        )
        post = Post.objects.get(pk=self.kwargs["pk"])
        recommend = (
            Post.objects.exclude(pk=self.kwargs["pk"])
            .filter(is_published=True)
            .order_by("-watched")[:5]
        )
        context["title"] = post.title
        context["recommend"] = recommend
        context["comments"] = Comment.objects.filter(post=post)
        if self.request.user.is_authenticated:
            context["comment_form"] = CommentForm
        return context


# def add_post(request: HttpRequest) -> HttpResponse:
#     """Додавання статті від користувача"""
#     if request.method == "POST":
#         form = PostAddForm(request.POST, request.FILES)
#         if form.is_valid():
#             post = Post.objects.create(**form.cleaned_data)
#             post.save()
#             return redirect("cooking:post_detail", post.pk)
#     else:
#         form = PostAddForm()
#     context = {"title": "Додати статтю", "form": form}
#     return render(request, "cooking/_acticle_add_form.html", context)


class AddPost(generic.CreateView):
    """Додавання статті від користувача"""

    form_class = PostAddForm
    template_name = "cooking/_article_add_form.html"
    extra_context = {"title": "Додати статтю"}

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class UpdatePost(generic.UpdateView):
    """Редагування статті"""

    model = Post
    form_class = PostAddForm
    template_name = "cooking/_article_add_form.html"
    extra_context = {"title": "Змінити статтю"}


class DeletePost(generic.DeleteView):
    """Видалення статті"""

    model = Post
    success_url = reverse_lazy("cooking:index")
    context_object_name = "post"


def add_comment(request: HttpRequest, post_id: int) -> HttpResponse:
    """Додаємо коментар"""
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(
            commit=False
        )  # commit=False щоб поки не записувало в БД
        comment.user = request.user
        comment.post = Post.objects.get(pk=post_id)
        comment.save()
        messages.success(request, "Ваш коментар успішно додано")
    return redirect("cooking:post_detail", post_id)


def user_login(request: HttpRequest) -> HttpResponse:
    """Аутентифікація користувача"""
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(
                request, "Ви успішно приєдналися до свого облікового запису"
            )
            return redirect("cooking:index")
    else:
        form = LoginForm()

    context = {"title": "Авторизація користувача", "form": form}
    return render(request, "cooking/_login_form.html", context)


def user_logout(request: HttpRequest) -> HttpResponse:
    """Вихід користувача"""
    logout(request)
    messages.success(request, "Ви успішно вийшли з облікового запису")
    return redirect("cooking:index")


def user_register(request: HttpRequest) -> HttpResponse:
    """Реєстрація користувача"""
    if request.method == "POST":
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Ви успішно зареєстрували акаунт")
            return redirect("cooking:login")
    else:
        form = RegistrationForm()

    context = {"title": "Реєстрація користувача", "form": form}
    return render(request, "cooking/_register_form.html", context)


class SearchResult(Index):
    """Пошук слова у заголовку та у змісті статей"""

    def get_queryset(self):
        word = self.request.GET.get("q")
        posts = Post.objects.filter(
            Q(title__icontains=word) | Q(content__icontains=word)
        )
        return posts


def profile(request: HttpRequest, user_id: int) -> HttpResponse:
    """Сторінка користувача"""
    user = User.objects.get(pk=user_id)
    posts = Post.objects.filter(author=user)
    context = {
        "title": "Персональні данні",
        "user": user,
        "posts": posts,
    }
    return render(request, "cooking/profile.html", context)


class UserChangePassword(PasswordChangeView):
    """Простий спосіб зміни пароля користувача"""

    template_name = "cooking/password_change_form.html"
    success_url = reverse_lazy("cooking:index")


class CookingAPI(ListAPIView):
    """Видасть всі статті по API"""
    queryset = Post.objects.filter(is_published=True)
    serializer_class = PostSerializer


class CookingAPIDetail(RetrieveAPIView):
    """Видасть одну статтю по API"""
    queryset = Post.objects.filter(is_published=True)
    serializer_class = PostSerializer
    permission_classes = [IsAuthenticated]


class CategoryAPI(ListAPIView):
    """Видасть всі категорії по API"""
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class CategoryAPIDetail(RetrieveAPIView):
    """Видасть одну категорію по API"""
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

cooking/templates/cooking/_acticle_add_form.html
{% extends "base.html" %}



{% block main %}

	<!-- Add post-->
	<div class="d-flex justify-content-center">
		<div class="card col-8 mb-4 mt-4">
			<div class="card-body">
				<h2 class="text-center">Додавання нової статті</h2>
				<form action="" method="post" enctype="multipart/form-data">
					<!--  Fields for filling-->
					{% csrf_token %}
					<div>
					{{ form.as_p }}
					</div>
					<button class="btn btn-dark" type="submit">Добавить статью</button>
				</form>
			</div>
		</div>
	</div>
	<div>
		<div style="margin-top: 100px;"></div>
	</div>
{% endblock %}

cooking/templates/cooking/_article_detail.html
{% extends "base.html" %}

{% block main %}
	<div class="d-flex justify-content-between">
		<div class="col-8">
			<div class="card">
				<div class="card-header d-flex justify-content-between">{{ post.category }}
					<div>
						{% if request.user == post.author %}
							<a href="{% url "cooking:post_update" pk=post.pk %}" class="btn btn-dark">Змінити</a>
							<a href="{% url "cooking:post_delete" pk=post.pk %}" class="btn btn-dark">Видалити</a>
						{% endif %}
						<a href="{% url "cooking:category_list" pk=post.category.pk %}" class="btn btn-dark">Назад</a>
					</div>
				</div>
				<img src="" class="card-img-top" alt="">
				<div class="card-body">
					{% if post.photo %}
						<img src="{{ post.photo.url }}" height="200" alt="">
					{% else %}
						<img src="https://www.raumplus.ru/upload/iblock/99e/Skoro-zdes-budet-foto.jpg" width="300" alt="">
					{% endif %}
					<h5 class="card-title">{{ post.title }}</h5>
					<p class="card-text">{{ post.content | linebreaks }}</p>
				</div>
				<div class="card-footer d-flex justify-content-between"><p class="card-text">{{ post.created_at }}</p>
					<a href="{% url "cooking:profile" post.author.pk %}">Автор статті: {{ post.author }}</a>
					<p class="card-text">{{ post.watched }}</p>
				</div>
			</div>
			<hr>

			<!--  reviews-->
			{% if request.user.is_authenticated %}
				<form action="{% url "cooking:add_comment" post.pk %}" method="post" , enctype="multipart/form-data">
					{% csrf_token %}
					{% include "components/_form_errors.html" %}
					{{ comment_form.text }}
					<button class="btn btn-dark" type="submit">Додати коментарій</button>
				</form>
			{% endif %}
			{% for comment in comments %}
				<div class="card mt-2">
					<div class="card-header d-flex justify-content-between">
						<h5><span>{{ comment.user }}</span></h5>
						<span class="text-muted small align-self-end">{{ comment.created_at }}</span>
					</div>
					<div class="card-body">
						<p class="card-text">{{ comment.text }}</p>
					</div>
				</div>
			{% endfor %}
		</div>
		<!--  Recommendation-->
		<div class="col-1"></div>
		<div class="col-4">
			{% for post_rec in recommend %}
				<div class="card" style="width: 18rem;">
					{% if post_rec.photo %}
						<img src="{{ post_rec.photo.url }}" width="200" alt="">
					{% else %}
						<img class="card-img-top" src="https://www.raumplus.ru/upload/iblock/99e/Skoro-zdes-budet-foto.jpg"
						     width="200"
						     alt="">
					{% endif %}
					<div class="card-body"><h5 class="card-title">{{ post_rec.title }}</h5><a
							href="{{ post_rec.get_absolute_url }}" class="btn btn-primary">Детальніше</a></div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

cooking/templates/cooking/article_detail.html
{% extends "base.html" %}

{% block main %}
	<div class="d-flex justify-content-between">
		<div class="col-8">
			<div class="card">
				<div class="card-header d-flex justify-content-between">{{ post.category }}
					<div>
						<a href="#!" class="btn btn-dark">Удалить</a>
						<a href="#!" class="btn btn-dark">Изменить</a>
						<a href="#!" class="btn btn-dark">Назад</a>
					</div>
				</div>
				<img src="" class="card-img-top" alt="">
				<div class="card-body">
					{% if post.photo %}
						<img src="{{ post.photo.url }}" height="200" alt="">
					{% else %}
						<img src="https://www.raumplus.ru/upload/iblock/99e/Skoro-zdes-budet-foto.jpg" width="300" alt="">
					{% endif %}
					<h5 class="card-title">{{ post.title }}</h5>
					<p class="card-text">{{ post.content | linebreaks }}</p>
				</div>
				<div class="card-footer d-flex justify-content-between"><p class="card-text">{{ post.created_at }}</p>
					<a href="/profile/1">Автор статьи: Какой то человек</a>
					<p class="card-text">{{ post.watched }}</p>
				</div>
			</div>
			<hr>

			<!--  reviews-->
			<form action="#!" method="post" , enctype="multipart/form-data">
				<input type="hidden" name="csrfmiddlewaretoken"
				       value="dVpvJs374bq08P5ZzKsB7pSNUnoJ6PXRIDRXHc1fjvFIdKmbXrQMDMR0wYHLFtut">
				<textarea name="text" cols="40" rows="10" class="form-control" placeholder="Текст вашего комментария" required
				          id="id_text"></textarea>
				<button class="btn btn-dark" type="submit">Додати коментарій</button>
			</form>

			<div class="card mt-2"><h5 class="card-header">Какой то человек</h5>
				<div class="card-body">
					<p class="card-text">Текст отзыва</p>
				</div>
			</div>
		</div>
		<!--  Recommendation-->
		<div class="col-1"></div>
		<div class="col-4">
			{% for post_rec in recommend %}
				<div class="card" style="width: 18rem;">
				{% if post_rec.photo %}
					<img src="{{ post_rec.photo.url }}" width="200" alt="">
					{% else %}
					<img class="card-img-top" src="https://www.raumplus.ru/upload/iblock/99e/Skoro-zdes-budet-foto.jpg" width="200"
				     alt="">
				{% endif %}
				<div class="card-body"><h5 class="card-title">{{ post_rec.title }}</h5><a href="{{ post_rec.get_absolute_url }}" class="btn btn-primary">Детальніше</a></div>
			</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

cooking/templates/cooking/profile.html
{% extends "base.html" %}

{% block main %}
	<main>
		<div class="container">
			<div class="main-body">
				<div class="row gutters-sm">
					<div class="col-md-4 mb-3">
						<div class="card">
							<div class="card-body">
								<div class="d-flex flex-column align-items-center text-center">
									<img src="https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-PNG-Photos.png" alt="Admin"
									     class="rounded-circle" width="150">
									<div class="mt-3">
										<h4>{{ user.first_name }} {{ user.last_name }}</h4>
										<p class="text-secondary mb-1">Python Developer</p>
										<p class="text-muted font-size-sm">Tashkent, Uzbekistan</p>
										<button class="btn btn-primary">Follow</button>
										<button class="btn btn-outline-primary">Message</button>
									</div>
									<a href="{% url "cooking:change_password" %}" class="dropdown-item">Змінити пароль</a>
								</div>
							</div>
						</div>
						<div class="card mt-3">
							<ul class="list-group list-group-flush">
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0">
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
										     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
										     class="feather feather-globe mr-2 icon-inline">
											<circle cx="12" cy="12" r="10"></circle>
											<line x1="2" y1="12" x2="22" y2="12"></line>
											<path
													d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path>
										</svg>
										Website
									</h6>
									<span class="text-secondary">https://distro.uz</span>
								</li>
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0">
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
										     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
										     class="feather feather-github mr-2 icon-inline">
											<path
													d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path>
										</svg>
										Github
									</h6>
									<span class="text-secondary">Вася Пупкин</span>
								</li>

								</li>
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0">
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
										     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
										     class="feather feather-instagram mr-2 icon-inline text-danger">
											<rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
											<path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
											<line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
										</svg>
										Instagram
									</h6>
									<span class="text-secondary">Вася Пупкин</span>
								</li>
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0">
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
										     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
										     class="feather feather-facebook mr-2 icon-inline text-primary">
											<path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path>
										</svg>
										Facebook
									</h6>
									<span class="text-secondary">Вася Пупкин</span>
								</li>
							</ul>
						</div>
					</div>
					<div class="col-md-8">
						<div class="card mb-3">
							<div class="card-body">
								<div class="row">
									<div class="col-sm-3">
										<h6 class="mb-0">Full name</h6>
									</div>
									<div class="col-sm-9 text-secondary">
										{{ user.first_name }} {{ user.last_name }}
									</div>
								</div>
								<hr>
								<div class="row">
									<div class="col-sm-3">
										<h6 class="mb-0">Email</h6>
									</div>
									<div class="col-sm-9 text-secondary">
										{{ user.email }}
									</div>
								</div>
								<hr>
								<div class="row">
									<div class="col-sm-3">
										<h6 class="mb-0">Phone</h6>
									</div>
									<div class="col-sm-9 text-secondary">
										+99 (899) 98989898
									</div>
								</div>
								<hr>
								<div class="row">
									<div class="col-sm-3">
										<h6 class="mb-0">Mobile</h6>
									</div>
									<div class="col-sm-9 text-secondary">
										+99 (899) 98989889
									</div>
								</div>
								<hr>
								<div class="row">
									<div class="col-sm-3">
										<h6 class="mb-0">Address</h6>
									</div>
									<div class="col-sm-9 text-secondary">
										Tashkent, Uzbekistan
									</div>
								</div>
								<hr>
								<div class="row">
									<div class="col-sm-12">
										<a class="btn btn-info " target="__blank"
										   href="https://www.bootdey.com/snippets/view/profile-edit-data-and-skills">Edit</a>
									</div>
								</div>
							</div>
						</div>
						<!-- Author Posts-->
						{% for post in posts %}
							<div class="card p-3 mb-2">
								<div class="d-flex justify-content-between">
									<div class="card-text">{{ post.title }}</div>
									<div class="d-flex justify-content-between">
										<div>Перегляди: {{ post.watched }}</div>
										{% if request.user == post.author %}
											<div>
												<a href="{% url "cooking:post_update" post.pk %}" class="btn btn-info btn-sm"><i
														class="fa-solid fa-pen-to-square fs-5">Змінити</i></a>
											</div>
											<div>
												<a href="{% url "cooking:post_delete" post.pk %}" class="btn btn-danger btn-sm">
													<i class="fa-solid fa-xmark fs-5">Видалити</i>
												</a>
											</div>
										{% endif %}
									</div>
								</div>
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</main>
{% endblock %}