conf/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("cooking.urls", namespace="cooking")),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cooking/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from rest_framework_simplejwt.views import (
    TokenObtainPairView, TokenRefreshView
)

from cooking import views

app_name = "cooking"

urlpatterns = [
    # path("", cache_page(60 * 3)(views.Index.as_view()), name="index"), # Хешування на базі index.html
    path("", views.Index.as_view(), name="index"),
    path(
        "category/<int:pk>/",
        views.ArticleByCategory.as_view(),
        name="category_list"
    ),
    path("post/<int:pk>", views.PostDetail.as_view(), name="post_detail"),
    path("add_arcticle/", views.AddPost.as_view(), name="add_post"),
    path("post/<int:pk>/update/", views.UpdatePost.as_view(), name="post_update"),
    path("post/<int:pk>/delete/", views.DeletePost.as_view(), name="post_delete"),
    path("search/", views.SearchResult.as_view(), name="search"),
    path(
        "password/",
        views.UserChangePassword.as_view(),
        name="change_password",
    ),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("register/", views.user_register, name="register"),
    path("add_comment/<int:post_id>/", views.add_comment, name="add_comment"),
    path("profile/<int:user_id>/", views.profile, name="profile"),

    # API
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("posts/api/", views.CookingAPI.as_view(), name="cooking_api"),
    path("posts/api/<int:pk>", views.CookingAPIDetail.as_view(), name="cooking_api_detail"),
    path("categories/api/", views.CategoryAPI.as_view(), name="category_api"),
    path("categories/api/<int:pk>", views.CategoryAPIDetail.as_view(), name="category_api_detail"),
]

templates/components/_footer.html
<footer class="bg-light text-center text-lg-start">
	<div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0);">© 2023 Copyright:<a class="text-dark"
	                                                                                             href="https://mdbootstrap.com/">www.micros.uz</a>
	</div>
</footer>

templates/components/_form_errors.html
{% if form.errors %}
	<div class="form-error">
		{% for field in form %}
			{% for error in field.errors %}
				<div class="alert alert-danger" role="alert">
					{{ error }}
				</div>
			{% endfor %}
		{% endfor %}
		{% for non_field_error in form.non_field_errors %}
			<div class="alert alert-danger" role="alert">
				{{ non_field_error }}
			</div>
		{% endfor %}
	</div>
{% endif %}

templates/components/_messages.html
{% if messages %}
	<div class="message">
		{% for message in messages %}
			<div class="alert alert-{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %}" role="alert">
				{{ message }}
			</div>
		{% endfor %}

	</div>
{% endif %} 

templates/components/_navbar.html
{% load static %}

<header>
	<div class="container">
		<nav class="navbar navbar-expand-lg bg-light">
			<div class="container-fluid">
				<a class="navbar-brand" href="#!">
					<img src="{% static "img/logo.jpg" %}" width="60" alt="">
				</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
				        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Перемикач навігації"><span
						class="navbar-toggler-icon"></span></button>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item"><a class="nav-link active" aria-current="page"
						                        href="{% url "cooking:index" %}">Головна</a></li>
					</ul>
					<div class="d-flex">
						<form class="d-flex" role="search" method="get" action="{% url "cooking:search" %}">
							<input name="q" class="form-control me-2" type="search" placeholder="Пошук" aria-label="Пошук">
							<button class="btn btn-outline-success" type="submit">Пошук</button>
						</form>
						<ul class="navbar-nav me-auto mb-2 mb-lg-0">
							<!--  Users-->
							{% if not request.user.is_authenticated %}
								<li class="nav-item">
									<a class="nav-link active" aria-current="page" href="{% url "cooking:login" %}">Увійти</a>
								</li>
								<li class="nav-item">
									<a class="nav-link active" aria-current="page" href="{% url "cooking:register" %}">Зареєструватись</a>
								</li>

							{% else %}
								<li class="nav-item dropdown">
									<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
									   data-bs-toggle="dropdown" aria-expanded="false">
										Вітаю {{ request.user.username }}!
									</a>
									<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
										<li><a class="dropdown-item" href="{% url "cooking:profile" request.user.pk %}">Моя сторінка</a></li>
										<li><a class="dropdown-item" href="{% url "cooking:add_post" %}">Додати статтю</a></li>
										<li>
											<hr class="dropdown-divider">
										</li>
										<li><a class="dropdown-item" href="{% url "cooking:logout" %}">Вихід</a></li>
									</ul>
								</li>
							{% endif %}

						</ul>
					</div>
				</div>
			</div>
		</nav>
	</div>
</header>